-- 0026_tasks_add_claude_prompt.sql
--
-- Adds a claude_prompt column to public.tasks and populates it for
-- every task currently owned by 'me' (Claude). The /admin/tasks UI
-- renders a "Copy prompt for Claude" button on every row where this
-- column is non-null; the founder pastes the result into a fresh
-- Claude session to kick off the work without re-explaining context.
--
-- Each prompt is self-contained:
--   - States the repo path
--   - Names CLAUDE.md / AGENTS.md so the new session reads the rules
--   - References specific file paths + line numbers
--   - Quotes the current code briefly
--   - Names the desired change
--   - Calls out any decisions the founder needs to make inline
--   - Ends with build + commit + push + mark-done instructions

alter table public.tasks
  add column if not exists claude_prompt text;

-- =====================================================================
-- NOW tier prompts
-- =====================================================================

update public.tasks set claude_prompt = E'You are working on the Veroax codebase at ~/veroax-marketing. Read CLAUDE.md and AGENTS.md first (in particular the no-em-dashes rule).\n\nTask: fix the DRE name matcher in lib/server/dreVerify.ts (the `nameMatchesDre` function, around line 180). The current `normalize()` helper strips apostrophes, hyphens, and accented characters via this regex:\n\n  s.toLowerCase().replace(/[^a-z\\s,]/g, "")\n\nThat falsely returns ''mismatch'' for real California agents named O''Connor, D''Angelo, Mary-Jane, Jose, etc.\n\nFix the normalize() function:\n1. Add Unicode decomposition + diacritic stripping BEFORE lowercasing: `.normalize("NFD").replace(/[\\u0300-\\u036f]/g, "")` so Jose becomes Jose, Munoz becomes Munoz.\n2. Change the allowlist from `/[^a-z\\s,]/g` to `/[^a-z\\s,''-]/g` so apostrophes and hyphens survive.\n\nThen: npm run build (must pass), git commit with a descriptive message in the project''s established style (look at recent git log), git push origin main. Mark this task done at /admin/tasks.'
where title = 'Fix DRE name matcher to handle apostrophes / hyphens / accented characters'
  and category = 'now';

update public.tasks set claude_prompt = E'You are working on the Veroax codebase at ~/veroax-marketing. Read CLAUDE.md and AGENTS.md first.\n\nTask: fix the GA dashboard deep link on /admin/integrations. The file is app/admin/integrations/page.tsx around line 47. It currently builds:\n\n  https://analytics.google.com/analytics/web/#/p${encodeURIComponent(config.google_analytics_id)}/reports/dashboard\n\nThat tries to use the GA Measurement ID (G-XXXXXXX) but GA dashboard URLs need the numeric Property ID (like 123456789). Link 404s.\n\nFix: change the href to simply `https://analytics.google.com/` and let GA''s own property selector pick the right one based on the signed-in user. Update any surrounding label text if needed to stay accurate.\n\nThen: npm run build, git commit, git push origin main. Mark this task done at /admin/tasks.'
where title = 'Fix GA dashboard deep link on /admin/integrations'
  and category = 'now';

update public.tasks set claude_prompt = E'You are working on the Veroax codebase at ~/veroax-marketing. Read CLAUDE.md and AGENTS.md first.\n\nTask: in app/_components/GoogleAnalytics.tsx around line 34, wrap the measurement ID interpolation in JSON.stringify. Current:\n\n  gtag(''config'', ''${measurementId}'', { send_page_view: true });\n\nChange to:\n\n  gtag(''config'', ${JSON.stringify(measurementId)}, { send_page_view: true });\n\nThis is defense-in-depth: the regex validation makes it safe today, but JSON.stringify is the correct primitive for server-rendered JS-context interpolation. Same behavior, no runtime cost.\n\nThen: npm run build, git commit, git push origin main. Mark this task done at /admin/tasks.'
where title = 'Wrap GA inline script interpolation in JSON.stringify'
  and category = 'now';

update public.tasks set claude_prompt = E'You are working on the Veroax codebase at ~/veroax-marketing. Read CLAUDE.md and AGENTS.md first.\n\nTask: fix lib/siteConfig.ts cache poisoning on transient DB errors. The `getSiteConfig` function around line 44-65 currently catches errors and caches the empty default config for 60s on ANY failure. A momentary Supabase hiccup leaves the site without GA tracking for up to 60s after recovery.\n\nFix: split the two failure modes apart.\n1. When `error` is non-null (real DB error): return the default WITHOUT writing to the cache, so the next call retries\n2. When `error` is null but `data` is null (genuine "no row found"): cache the default as before; this is a legitimate empty state\n\nThe outer try/catch should keep its current behavior (log + return default on uncaught exceptions, no caching).\n\nThen: npm run build, git commit, git push origin main. Mark this task done at /admin/tasks.'
where title = 'Fix getSiteConfig cache poisoning on transient DB error'
  and category = 'now';

-- =====================================================================
-- LAUNCH tier prompts
-- =====================================================================

update public.tasks set claude_prompt = E'You are working on the Veroax codebase at ~/veroax-marketing. Read CLAUDE.md and AGENTS.md first.\n\nTask: add Privacy + Terms links to the dashboard sidebar footer. The marketing footer (in app/page.tsx) has them; the dashboard footer in app/dashboard/layout.tsx does not. Logged-in users have no way to re-read them without leaving the dashboard.\n\nFind the support contact block in app/dashboard/layout.tsx (it has the (866) 247-8833 phone, support@veroax.com email, and the "Send feedback" link). Add two small text links below that block:\n  - "Terms" -> /terms\n  - "Privacy" -> /privacy\n\nStyle them consistently with the existing small footer text (slate-400 or similar, hover to white). Comma-separate or pipe-separate as appropriate; keep them compact.\n\nThen: npm run build, git commit, git push origin main. Mark this task done at /admin/tasks.'
where title = 'Add Privacy + Terms links to dashboard footer'
  and category = 'launch';

update public.tasks set claude_prompt = E'You are working on the Veroax codebase at ~/veroax-marketing. Read CLAUDE.md and AGENTS.md first (no em dashes anywhere, including in code comments).\n\nTask: create lib/site.ts as a single source of truth for support contact info. Currently the phone (866) 247-8833, hours ("8:00 AM to 8:00 PM Pacific, every day"), email support@veroax.com, and Santa Clara mailing address are hardcoded across roughly 10 files.\n\nStep 1: create lib/site.ts exporting:\n  export const SUPPORT = {\n    phone: "(866) 247-8833",\n    phoneTel: "+18662478833",\n    email: "support@veroax.com",\n    hours: "8:00 AM to 8:00 PM Pacific, every day",\n    address: {\n      street: "3964 Rivermark Plaza Unit #2783",\n      city: "Santa Clara",\n      region: "CA",\n      postalCode: "95054",\n    },\n  } as const;\n\nStep 2: grep the codebase for hardcoded "866" or "247-8833" or "veroax.com" support strings. Replace usages with SUPPORT.* imports. Files to check (non-exhaustive):\n  - app/page.tsx\n  - app/contact/page.tsx\n  - app/contact/_components/ContactForm.tsx\n  - app/dashboard/layout.tsx\n  - app/privacy/page.tsx\n  - lib/email/welcomeEmail.ts\n  - lib/email/adminSignupNotification.ts\n\nLeave the email "from:" addresses alone (separate task), only consolidate the user-facing references.\n\nThen: npm run build, git commit, git push origin main. Mark this task done at /admin/tasks.'
where title = 'Consolidate support constants to lib/site.ts'
  and category = 'launch';

update public.tasks set claude_prompt = E'You are working on the Veroax codebase at ~/veroax-marketing. Read CLAUDE.md and AGENTS.md first.\n\nTask: improve app/sitemap.ts so the lastModified field reflects actual deploy time, not the moment-of-generation. Currently every static page''s lastModified is `new Date()`, so Google sees every page as "modified just now" on every crawl, which degrades the priority signal.\n\nFix:\n1. At the top of sitemap.ts, read `process.env.VERCEL_GIT_COMMIT_DATE` (Vercel exports this on every build). It is an ISO timestamp.\n2. If unset (local dev), fall back to `new Date()`.\n3. Use that value for every static page''s lastModified.\n4. Leave blog posts alone, they already use `new Date(post.publishedAt)` which is correct.\n\nThen: npm run build, git commit, git push origin main. Mark this task done at /admin/tasks.'
where title = 'Improve sitemap lastModified to use deploy time'
  and category = 'launch';

-- =====================================================================
-- DEFERRED tier prompts
-- =====================================================================

update public.tasks set claude_prompt = E'You are working on the Veroax codebase at ~/veroax-marketing. Read CLAUDE.md and AGENTS.md first.\n\nTask: implement a DRE verification gate on report PDF generation. Currently agents whose DRE has not been verified (or has failed verification) can still ship branded PDFs to clients; they''re only flagged on /admin/users.\n\nBefore building, decide between three policies based on real-world verification data (check /admin/users for the current pass/fail distribution):\n  (a) Hard block: status != ''verified'' means PDF render returns a 412 with a "verify your DRE first" message\n  (b) Watermark: render the PDF but with a "Verification Pending" overlay similar to the existing trial watermark\n  (c) Soft flag only (current behavior)\n\nRecommendation: ship (b) as the most product-friendly. The route to modify is app/api/reports/[id]/pdf/route.tsx; it already has a `watermarked` flag for trial accounts. Add a parallel `verificationPending` flag that triggers similar overlay logic in ReportPDF.\n\nAsk the founder if uncertain which policy to ship.\n\nThen: npm run build, git commit, git push origin main. Mark this task done at /admin/tasks.'
where title = 'Implement DRE PDF gate for unverified accounts'
  and category = 'deferred';

update public.tasks set claude_prompt = E'You are working on the Veroax codebase at ~/veroax-marketing. Read CLAUDE.md and AGENTS.md first.\n\nTask: add a Vercel cron job that re-runs DRE verification weekly for every profile whose `dre_verified_at` is older than 30 days OR whose status is ''error''. Catches license expirations + retries transient errors.\n\nSteps:\n1. New route at app/api/cron/dre-resweep/route.ts (mirror the pattern of app/api/cron/sweep-stale-reports/route.ts)\n2. Auth-gate via CRON_SECRET header (same pattern as the existing cron)\n3. Query profiles where dre_license is not null AND (dre_verified_at is null OR dre_verified_at < now() - interval ''30 days'' OR dre_verification_status = ''error''), limit 50 per run (rate-limit politeness toward the DRE site)\n4. For each, call verifyDreLicense() + persistDreResult() from lib/server/dreVerify.ts\n5. Log a summary to console (how many checked, how many flipped status)\n6. Add to vercel.json crons: weekly at 03:00 UTC Monday\n\nThen: npm run build, git commit, git push origin main. Tell founder to redeploy so Vercel picks up the new cron. Mark this task done at /admin/tasks.'
where title = 'Cron job for periodic DRE re-verification'
  and category = 'deferred';

update public.tasks set claude_prompt = E'You are working on the Veroax codebase at ~/veroax-marketing. Read CLAUDE.md and AGENTS.md first.\n\nTask: give brokerage admins the same roster controls the site admin currently has under /admin/brokerages/[id]. Today brokerage admins land on /dashboard/brokerage and can only VIEW their teams + agents; site admin does removals + transfers from /admin/.\n\nAdd to /dashboard/brokerage:\n1. For each team listed: an "Edit team" button that opens a small panel with rename + transfer-owner controls\n2. For each direct agent: a "Remove from brokerage" button (with confirmation modal)\n3. Pending invites section: a "Revoke" button on each row\n\nAll actions go through new API routes at app/api/brokerage/* (mirror the patterns under app/api/admin/brokerages/* but gate on isBrokerageAdmin() from lib/brokerage/admin.ts, not is_admin). Audit-log every mutation.\n\nThen: npm run build, git commit, git push origin main. Mark this task done at /admin/tasks.'
where title = 'Brokerage-side roster controls'
  and category = 'deferred';

update public.tasks set claude_prompt = E'You are working on the Veroax codebase at ~/veroax-marketing. Read CLAUDE.md and AGENTS.md first (no React-PDF property reintroductions: no border-*, no position:absolute on footer, etc.; the AGENTS.md and recent commits list the forbidden set).\n\nTask: extend ReportPDF.tsx to render BOTH brokerage AND team branding when a report has both stamped. Today the resolver in lib/pdf-render/branding.ts picks one (team wins).\n\nSteps:\n1. Add a `parentBrokerage` prop to ReportPDF: optional, contains brokerage logo + DRE\n2. In the cover layout, render parentBrokerage in a small "Brokerage of:" header strip ABOVE the main brand block when present\n3. Main brand block continues to use the team-or-agent branding\n4. Update lib/pdf-render/branding.ts: when both brokerage_id and team_id are set, return both as two separate prop sets, not a merged one\n5. Update app/api/reports/[id]/pdf/route.tsx, /email/send/route.tsx, and /r/[code]/pdf/route.tsx to pass parentBrokerage where applicable\n\nThen: npm run build, git commit, git push origin main. Mark this task done at /admin/tasks.'
where title = 'PDF cover with BOTH brokerage AND team branding'
  and category = 'deferred';

update public.tasks set claude_prompt = E'You are working on the Veroax codebase at ~/veroax-marketing. Read CLAUDE.md and AGENTS.md first.\n\nTask: let an agent remove a file they uploaded to a report. If the report has already been analyzed, removing a file should force a re-analysis.\n\nSteps:\n1. On app/dashboard/reports/[id]/page.tsx, add a "Remove" button next to each file in the document inventory list\n2. Confirmation modal: "Removing X will trigger a fresh analysis. Continue?"\n3. New route POST /api/reports/[id]/remove-file with body { filename: string }\n4. Route deletes the file from Supabase Storage (disclosures bucket), removes the corresponding entry from reports.original_files, then:\n   - If status was ''qa_pending'' / ''qa_approved'' / ''delivered'': set status = ''analyzing'' and call performAnalysis() via after()\n   - Otherwise: just persist the removal\n5. Audit-log the action\n\nMirror the existing patterns in app/api/reports/[id]/update/route.ts and the existing /finalize for storage + analysis coordination.\n\nThen: npm run build, git commit, git push origin main. Mark this task done at /admin/tasks.'
where title = 'File removal with forced re-analysis'
  and category = 'deferred';

update public.tasks set claude_prompt = E'You are working on the Veroax codebase at ~/veroax-marketing. Read CLAUDE.md and AGENTS.md first.\n\nTask: add an in-app traffic widget to /admin showing GA pageview data. Lets the founder see traffic without leaving Veroax.\n\nSteps:\n1. The Google Analytics Data API requires OAuth + a service account. Walk the founder through creating a Google Cloud project, enabling the GA Data API, creating a service account, downloading the credentials JSON, and adding the service account email as a viewer on the GA property\n2. Add env vars: GOOGLE_SERVICE_ACCOUNT_EMAIL, GOOGLE_SERVICE_ACCOUNT_KEY (base64-encoded JSON), GA_PROPERTY_ID (numeric)\n3. Create lib/server/ga.ts with helpers: getPageViewsLast30Days(), getTopPagesLast30Days(), getTopSourcesLast30Days(). Cache results for 1 hour (in-memory or Supabase row)\n4. Render a "Traffic" card on app/admin/page.tsx showing: total pageviews (30d), top 5 pages, top 5 sources\n5. Link out to the full GA dashboard for detail\n\nWait until the founder confirms they want this AND has at least a month of real GA data flowing before building.\n\nThen: npm run build, git commit, git push origin main. Mark this task done at /admin/tasks.'
where title = 'In-app analytics widget on /admin'
  and category = 'deferred';

-- =====================================================================
-- POLISH tier prompts
-- =====================================================================

update public.tasks set claude_prompt = E'You are working on the Veroax codebase at ~/veroax-marketing. Read CLAUDE.md and AGENTS.md first.\n\nTask: improve phone normalization in app/(auth)/actions.ts (function normalizePhone, around line 37) to add ''+1'' when the digits look like a 10-digit US number missing the country code.\n\nCurrent behavior: ''(415) 555-0100'' becomes ''4155550100'' (no plus, no country code). The SalesAndMarketing.ai integration prefers E.164.\n\nFix:\n1. After extracting digits, if the input had no leading ''+'' AND digits.length === 10, prepend ''+1''\n2. If digits.length === 11 and starts with ''1'' AND no leading plus, prepend ''+''\n3. Otherwise leave as-is\n\nKeep returning null when no digits found at all.\n\nThen: npm run build, git commit, git push origin main. Mark this task done at /admin/tasks.'
where title = 'Phone normalization: add +1 country code when missing'
  and category = 'polish';

update public.tasks set claude_prompt = E'You are working on the Veroax codebase at ~/veroax-marketing. Read CLAUDE.md and AGENTS.md first.\n\nTask: consolidate the three separate `after()` callbacks in app/(auth)/actions.ts (signupAction, lines 134-192) into one parallel block using Promise.allSettled.\n\nCurrent structure has three after() invocations: welcome email, admin notification, CRM sync. Each is independent but they share serialization in Vercel''s background-work budget.\n\nNew structure:\n  after(async () => {\n    await Promise.allSettled([\n      sendWelcomeEmail({ email, fullName }),\n      sendAdminSignupNotification({ status: "ok", ... }),\n      addContactToMarketingGroup({ ... }),\n    ]);\n  });\n\nLog rejections via console.error (one per failed task) so the existing telemetry still captures partial failures.\n\nKeep the error-path after() (the one that fires only when Supabase signUp errored) as a separate block.\n\nThen: npm run build, git commit, git push origin main. Mark this task done at /admin/tasks.'
where title = 'Consolidate signupAction three after() blocks into Promise.allSettled'
  and category = 'polish';

update public.tasks set claude_prompt = E'You are working on the Veroax codebase at ~/veroax-marketing. Read CLAUDE.md and AGENTS.md first. CRITICAL: do not reintroduce any React-PDF properties from the forbidden list (see AGENTS.md and recent commits in lib/pdf-render/ReportPDF.tsx for the full set).\n\nTask: refactor lib/pdf-render/ReportPDF.tsx (currently 2700+ lines) into smaller per-section subcomponents. No behavior change; pure structural refactor.\n\nApproach:\n1. Identify the major sections rendered on the cover + body pages (executive summary, property snapshot, critical findings, etc.)\n2. Extract each section as its own file under lib/pdf-render/sections/, with the same props it currently receives\n3. ReportPDF.tsx becomes a top-level shell that composes the sections\n4. Keep all styles in ReportPDF.tsx''s shared style sheet (sections import from there)\n5. Test by rendering a real report PDF end-to-end (via /api/reports/[id]/pdf) and visually diffing against the pre-refactor output\n\nThis is risky because React-PDF has many sharp edges. Make a backup branch first: `git checkout -b refactor/report-pdf`. Land the refactor on that branch, get the founder to spot-check three reports, THEN merge to main.\n\nThen: npm run build, git commit, git push origin refactor/report-pdf. Mark this task done at /admin/tasks ONLY after merge to main.'
where title = 'Refactor ReportPDF.tsx (2731 lines) into smaller modules'
  and category = 'polish';

update public.tasks set claude_prompt = E'You are working on the Veroax codebase at ~/veroax-marketing. Read CLAUDE.md and AGENTS.md first.\n\nTask: refactor lib/anthropic/analyze.ts (currently 2058 lines) into smaller modules. No behavior change; pure structural refactor.\n\nApproach:\n1. Identify the major sub-systems: prompt building (system prompt + per-group instructions), passes (the focused-pass orchestration), synthesis (combining pass outputs), retries (the wait + retry loop), telemetry/cost tracking\n2. Extract each into its own file under lib/anthropic/ (e.g., prompts.ts, passes.ts, synthesis.ts, retries.ts, telemetry.ts)\n3. analyze.ts becomes the top-level orchestrator that imports + composes\n4. Preserve all existing exports so external callers (lib/server/performAnalysis.ts) don''t need to change\n5. Verify by running a full analysis end-to-end on a test report\n\nMake a backup branch first: `git checkout -b refactor/analyze`. Land the refactor on that branch, get the founder to spot-check one full analysis, THEN merge to main.\n\nThen: npm run build, git commit, git push origin refactor/analyze. Mark this task done at /admin/tasks ONLY after merge to main.'
where title = 'Refactor lib/anthropic/analyze.ts (2058 lines) into smaller modules'
  and category = 'polish';

update public.tasks set claude_prompt = E'You are working on the Veroax codebase at ~/veroax-marketing. Read CLAUDE.md and AGENTS.md first.\n\nTask: in lib/server/dreVerify.ts, add a clarifying comment above the extractField regex (around line 125).\n\nThe regex has a double `(?:</a>)?` (before AND after the colon) which looks like a typo. It''s actually correct: the DRE site renders labels in two formats:\n  - Plain: <strong>Name:</strong>\n  - Wrapped: <strong><A HREF="...">License Status</A>:</strong>\n\nIn the wrapped variant the closing </A> sits BEFORE the colon. Add a comment block above the regex explaining that the double `(?:</a>)?` covers both placements and noting why the colon is optional (`:?`).\n\nNo code change required, only documentation. Then: git commit, git push origin main. Mark this task done at /admin/tasks.'
where title = 'Add explanatory comment to extractField regex in dreVerify.ts'
  and category = 'polish';

update public.tasks set claude_prompt = E'You are working on the Veroax codebase at ~/veroax-marketing. Read CLAUDE.md and AGENTS.md first.\n\nTask: audit all <img> tags in app/ for empty or missing alt attributes. The brand-page sweep (commit b713761) covered app/brand/*. Other pages may still have alt="" or missing alt entirely.\n\nSteps:\n1. grep -rn ''alt=""'' app/ to find empty alts\n2. grep -rn ''<img '' app/ then filter for tags lacking alt= entirely\n3. For each finding, replace with a descriptive alt that names what the image shows (logo variant, headshot, brokerage logo, etc.)\n4. Skip purely-decorative images that already have alt="" intentionally (rare)\n\nThen: npm run build, git commit, git push origin main. Mark this task done at /admin/tasks.'
where title = 'Audit remaining img tags for alt text'
  and category = 'polish';

-- Migration registration.
insert into public._migrations(name) values ('0026_tasks_add_claude_prompt')
  on conflict (name) do nothing;
